### ISSUE TITLE
KeyError: 'head'

### ISSUE THREAD

**Issue by yywhsgnd** [apoorvumang/CronKGQA#18]
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jupyter/miniforge3/envs/env8/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jupyter/miniforge3/envs/env8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jupyter/miniforge3/envs/env8/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jupyter/workspace/CronKGQA-main/qa_datasets.py", line 372, in __getitem__
    head = data['head'][index]
KeyError: 'head'

**Comment by 652994331** [comment]
@yywhsgnd  hi, I met the same question, have u solved it ?

**Comment by xrokie** [comment]
`question_text = 'What is the name of the first team that Q1487425 was part of'
entities = getEntities(question_text)
times = []
dataPoint = convertToDataPoint(question_text, entities, times)
data = [dataPoint]
valid_dataset.data = data
valid_dataset.prepared_data = valid_dataset.prepare_data(data)

predict(qa_model, valid_dataset)`

In this code block, here he lost an under-dash, where the function should be 'valid_dataset.prepared_data = valid_dataset.prepare_data_(data)'
